FROM nginx 
#On charge l'image de NGINX
COPY index.html /usr/share/nginx/html/index.html
#On copie le fichier index.html dans le dossier "/usr/share/nginx/html/index.html" de notre conteneur pour que le serveur NGINX la retrouve et puisse la charger