--
-- scriptint Job
--
-- ==> permet de faire un script de sauvegarde des jobs
-- les jobs sont associés à l'instance et pas à une base
-- ssms : view > object Explorer Detail > ==> permet d'accéder au scripting
