
CREATE PRIMARY XML INDEX pidx_page ON CATALOGUES(page);
GO
CREATE XML INDEX idx_page_path ON CATALOGUES(page)
  USING XML INDEX pidx_page FOR PATH;
GO
CREATE XML INDEX idx_page_property ON CATALOGUES(page)
  USING XML INDEX pidx_page FOR PROPERTY;
GO
CREATE XML INDEX idx_page_value ON CATALOGUES(page)
  USING XML INDEX pidx_page FOR VALUE;