CREATE UNIQUE CLUSTERED INDEX INOCLI
  ON CLIENTS (numero)
  WITH (FILLFACTOR=50);
go
CREATE INDEX I_LIGNES_REFART
  ON LIGNES_CDE(reference_art)
  INCLUDE (numero_cde);
go
CREATE INDEX IDESIGNATION_ARTICLES
  ON ARTICLES(designation_art)
  WHERE code_cat IN (1,2);
