INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (1001,
             1,
             'AB',
             'Alberta',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (1002,
             1,
             'BC',
             'British Columbia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (1003,
             1,
             'MB',
             'Manitoba',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (1004,
             1,
             'NB',
             'New Brunswick',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (1005,
             1,
             'NL',
             'Newfoundland and Labrador',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (1006,
             1,
             'NT',
             'Northwest Territories',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (1007,
             1,
             'NS',
             'Nova Scotia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (1008,
             1,
             'NU',
             'Nunavut',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (1009,
             1,
             'ON',
             'Ontario',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (1010,
             1,
             'PE',
             'Prince Edward Island',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (1011,
             1,
             'QC',
             'Quebec',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (1012,
             1,
             'SK',
             'Saskatchewan',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (1013,
             1,
             'YT',
             'Yukon',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2001,
             2,
             'CN-34',
             'Anhui',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2002,
             2,
             'CN-92',
             'Aomen',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2003,
             2,
             'CN-11',
             'Beijing',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2004,
             2,
             'CN-50',
             'Chongqing',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2005,
             2,
             'CN-35',
             'Fujian',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2006,
             2,
             'CN-62',
             'Gansu',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2007,
             2,
             'CN-44',
             'Guangdong',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2008,
             2,
             'CN-45',
             'Guangxi',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2009,
             2,
             'CN-52',
             'Guizhou',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2010,
             2,
             'CN-46',
             'Hainan',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2011,
             2,
             'CN-13',
             'Hebei',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2012,
             2,
             'CN-23',
             'Heilongjiang',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2013,
             2,
             'CN-41',
             'Henan',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2014,
             2,
             'CN-42',
             'Hubei',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2015,
             2,
             'CN-43',
             'Hunan',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2016,
             2,
             'CN-32',
             'Jiangsu',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2017,
             2,
             'CN-36',
             'Jiangxi',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2018,
             2,
             'CN-22',
             'Jilin',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2019,
             2,
             'CN-21',
             'Liaoning',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2020,
             2,
             'CN-15',
             'Nei Mongol',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2021,
             2,
             'CN-64',
             'Ningxia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2022,
             2,
             'CN-63',
             'Qinghai',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2023,
             2,
             'CN-61',
             'Shaanxi',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2024,
             2,
             'CN-37',
             'Shandong',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2025,
             2,
             'CN-31',
             'Shanghai',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2026,
             2,
             'CN-14',
             'Shanxi',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2027,
             2,
             'CN-51',
             'Sichuan',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2028,
             2,
             'CN-71',
             'Taiwan',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2029,
             2,
             'CN-12',
             'Tianjin',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2030,
             2,
             'CN-91',
             'Xianggang',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2031,
             2,
             'CN-65',
             'Xinjiang',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2032,
             2,
             'CN-54',
             'Xizang',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2033,
             2,
             'CN-53',
             'Yunnan',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (2034,
             2,
             'CN-33',
             'Zhejiang',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3001,
             3,
             'A',
             'Alsace',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3002,
             3,
             'B',
             'Aquitaine',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3003,
             3,
             'C',
             'Auvergne',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3004,
             3,
             'P',
             'Basse-Normandie',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3005,
             3,
             'D',
             'Bourgogne',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3006,
             3,
             'E',
             'Bretagne',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3007,
             3,
             'F',
             'Centre',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3008,
             3,
             'G',
             'Champagne-Ardenne',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3009,
             3,
             'H',
             'Corse',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3010,
             3,
             'GF',
             'Guyane',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3011,
             3,
             'I',
             'Franche Comté',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3012,
             3,
             'GP',
             'Guadeloupe',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3013,
             3,
             'Q',
             'Haute-Normandie',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3014,
             3,
             'J',
             'Île-de-France',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3015,
             3,
             'K',
             'Languedoc-Roussillon',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3016,
             3,
             'L',
             'Limousin',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3017,
             3,
             'M',
             'Lorraine',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3018,
             3,
             'MQ',
             'Martinique',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3019,
             3,
             'N',
             'Midi-Pyrénées',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3020,
             3,
             'O',
             'Nord Pas de Calais',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3021,
             3,
             'R',
             'Pays de la Loire',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3022,
             3,
             'S',
             'Picardie',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3023,
             3,
             'T',
             'Poitou-Charentes',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3024,
             3,
             'U',
             'Provence-Alpes-Côte-d''Azur',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3025,
             3,
             'RE',
             'Réunion',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (3026,
             3,
             'V',
             'Rhône-Alpes',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (4001,
             4,
             'BW',
             'Baden-Württemberg',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (4002,
             4,
             'BY',
             'Bayern',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (4003,
             4,
             'BE',
             'Berlin',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (4005,
             4,
             'HB',
             'Bremen',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (4006,
             4,
             'HH',
             'Hamburg',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (4007,
             4,
             'HE',
             'Hessen',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (4008,
             4,
             'MV',
             'Mecklenburg-Vorpommern',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (4009,
             4,
             'NI',
             'Niedersachsen',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (4010,
             4,
             'NW',
             'Nordrhein-Westfalen',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (4011,
             4,
             'RP',
             'Rheinland-Pfalz',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (4012,
             4,
             'SL',
             'Saarland',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (4013,
             4,
             'SN',
             'Sachsen',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (4014,
             4,
             'ST',
             'Sachsen-Anhalt',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (4015,
             4,
             'SH',
             'Schleswig-Holstein',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (4016,
             4,
             'TH',
             'Thüringen',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8001,
             8,
             'AG',
             'Agrigento',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8002,
             8,
             'AL',
             'Alessandria',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8003,
             8,
             'AN',
             'Ancona',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8004,
             8,
             'AO',
             'Aosta',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8005,
             8,
             'AR',
             'Arezzo',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8006,
             8,
             'AP',
             'Ascoli Piceno',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8007,
             8,
             'AT',
             'Asti',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8008,
             8,
             'AV',
             'Avellino',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8009,
             8,
             'BA',
             'Bari',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8010,
             8,
             'BT',
             'Barletta-Andria-Trani',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8011,
             8,
             'BL',
             'Belluno',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8012,
             8,
             'BN',
             'Benevento',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8013,
             8,
             'BG',
             'Bergamo',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8014,
             8,
             'BI',
             'Biella',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8015,
             8,
             'BO',
             'Bologna',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8016,
             8,
             'BZ',
             'Bolzano',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8017,
             8,
             'BS',
             'Brescia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8018,
             8,
             'BR',
             'Brindisi',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8019,
             8,
             'CA',
             'Cagliari',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8020,
             8,
             'CL',
             'Caltanissetta',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8021,
             8,
             'CB',
             'Campobasso',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8022,
             8,
             'CI',
             'Carbonia-Iglesias',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8023,
             8,
             'CE',
             'Caserta',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8024,
             8,
             'CT',
             'Catania',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8025,
             8,
             'CZ',
             'Catanzaro',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8026,
             8,
             'CH',
             'Chieti',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8027,
             8,
             'CO',
             'Como',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8028,
             8,
             'CS',
             'Cosenza',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8029,
             8,
             'CR',
             'Cremona',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8030,
             8,
             'KR',
             'Crotone',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8031,
             8,
             'CN',
             'Cuneo',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8032,
             8,
             'EN',
             'Enna',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8033,
             8,
             'FM',
             'Fermo',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8034,
             8,
             'FE',
             'Ferrara',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8035,
             8,
             'FI',
             'Firenze',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8036,
             8,
             'FG',
             'Foggia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8037,
             8,
             'FC',
             'Forli-Cesena',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8038,
             8,
             'FR',
             'Frosinone',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8039,
             8,
             'GE',
             'Genova',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8040,
             8,
             'GO',
             'Gorizia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8041,
             8,
             'GR',
             'Grosseto',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8042,
             8,
             'IM',
             'Imperia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8044,
             8,
             'AQ',
             'L''Aquila',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8046,
             8,
             'LT',
             'Latina',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8048,
             8,
             'LC',
             'Lecco',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8050,
             8,
             'LO',
             'Lodi',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8052,
             8,
             'MC',
             'Macerata',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8054,
             8,
             'MS',
             'Massa-Carrara',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8056,
             8,
             'MA',
             'Medio Campidano',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8058,
             8,
             'MI',
             'Milano',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8062,
             8,
             'NO',
             'Novara',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8064,
             8,
             'OG',
             'Ogliastra',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8066,
             8,
             'OR',
             'Oristano',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8068,
             8,
             'PA',
             'Palermo',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8070,
             8,
             'PV',
             'Pavia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8072,
             8,
             'PU',
             'Pesaro e Urbino',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8074,
             8,
             'PC',
             'Piacenza',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8076,
             8,
             'PT',
             'Pistoia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8078,
             8,
             'PZ',
             'Potenza',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8080,
             8,
             'RG',
             'Ragusa',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8082,
             8,
             'RC',
             'Reggio Calabria',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8084,
             8,
             'RI',
             'Rieti',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8086,
             8,
             'RM',
             'Roma',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8088,
             8,
             'SA',
             'Salerno',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8090,
             8,
             'SV',
             'Savona',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8092,
             8,
             'SR',
             'Siracusa',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8094,
             8,
             'TA',
             'Taranto',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8096,
             8,
             'TR',
             'Terni',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8098,
             8,
             'TP',
             'Trapani',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8100,
             8,
             'TV',
             'Treviso',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8102,
             8,
             'UD',
             'Udine',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8104,
             8,
             'VE',
             'Venezia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8106,
             8,
             'VC',
             'Vercelli',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8108,
             8,
             'VV',
             'Vibo Valentia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8110,
             8,
             'VT',
             'Viterbo',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (11002,
             11,
             'FL',
             'Flevoland',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (11004,
             11,
             'GE',
             'Gelderland',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (11006,
             11,
             'LI',
             'Limburg',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (11008,
             11,
             'NH',
             'Noord-Holland',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (11010,
             11,
             'UT',
             'Utrecht',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (11012,
             11,
             'ZH',
             'Zuid-Holland',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (15002,
             15,
             'AR',
             'Aragon',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (15004,
             15,
             'IB',
             'Balearic Islands',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (15006,
             15,
             'CN',
             'Canary Islands',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (15008,
             15,
             'CL',
             'Castile and Leon',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (15010,
             15,
             'CT',
             'Catalonia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (15012,
             15,
             'EX',
             'Extremadura',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (15014,
             15,
             'LO',
             'La Rioja',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (15016,
             15,
             'ML',
             'Melilla',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (15018,
             15,
             'NA',
             'Navarra',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19001,
             19,
             'AL',
             'Alabama',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19003,
             19,
             'AZ',
             'Arizona',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19005,
             19,
             'CA',
             'California',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19007,
             19,
             'CT',
             'Connecticut',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19009,
             19,
             'DE',
             'Delaware',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19011,
             19,
             'GA',
             'Georgia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19013,
             19,
             'ID',
             'Idaho',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19015,
             19,
             'IN',
             'Indiana',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19017,
             19,
             'KS',
             'Kansas',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19019,
             19,
             'LA',
             'Louisiana ',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19021,
             19,
             'MD',
             'Maryland',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19023,
             19,
             'MI',
             'Michigan',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19025,
             19,
             'MS',
             'Mississippi',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19027,
             19,
             'MT',
             'Montana',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19029,
             19,
             'NV',
             'Nevada',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19031,
             19,
             'NJ',
             'New Jersey',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19033,
             19,
             'NY',
             'New York',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19035,
             19,
             'ND',
             'North Dakota',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19037,
             19,
             'OK',
             'Oklahoma ',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19039,
             19,
             'PA',
             'Pennsylvania',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19041,
             19,
             'RI',
             'Rhode Island',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19043,
             19,
             'SD',
             'South Dakota',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19045,
             19,
             'TX',
             'Texas',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19047,
             19,
             'VT',
             'Vermont',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19049,
             19,
             'WA',
             'Washington',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19051,
             19,
             'WI',
             'Wisconsin',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (32001,
             32,
             'ACT',
             'Australian Capital Territory',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (32003,
             32,
             'NT',
             'Northern Territory',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (32005,
             32,
             'SA',
             'South Australia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (32007,
             32,
             'VIC',
             'Victoria',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144001,
             144,
             'MX-AGS',
             'Aguascalientes',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144003,
             144,
             'MX-BCS',
             'Baja California Sur',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144005,
             144,
             'MX-CHP',
             'Chiapas',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144007,
             144,
             'MX-COA',
             'Coahuila',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144009,
             144,
             'MX-DUR',
             'Durango',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144011,
             144,
             'MX-GRO',
             'Guerrero',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144013,
             144,
             'MX-JAL',
             'Jalisco',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144015,
             144,
             'MX-MIC',
             'Michoacan',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144017,
             144,
             'MX-NAY',
             'Nayarit',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144019,
             144,
             'MX-OAX',
             'Oaxaca',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144021,
             144,
             'MX-QRO',
             'Queretaro',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144024,
             144,
             'MX-SLP',
             'San Luis Potosí',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144026,
             144,
             'MX-SON',
             'Sonora',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144028,
             144,
             'MX-TAM',
             'Tamaulipas',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144030,
             144,
             'MX-VER',
             'Veracruz',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144032,
             144,
             'MX-ZAC',
             'Zacatecas',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (164002,
             164,
             '02',
             'Akershus',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (164004,
             164,
             '04',
             'Hedmark',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (164006,
             164,
             '06',
             'Buskerud',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (164008,
             164,
             '08',
             'Telemark',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (164010,
             164,
             '10',
             'Vest-Agder',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (164012,
             164,
             '12',
             'Hordaland',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (164014,
             164,
             '15',
             'Møre of Romsdal',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (164016,
             164,
             '17',
             'Nord-Trøndelag',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (164018,
             164,
             '19',
             'Troms',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202001,
             202,
             'AG',
             'Aargau',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202003,
             202,
             'AI',
             'Appenzell Innerrhoden',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202005,
             202,
             'BS',
             'Basel-Stadt',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202007,
             202,
             'FR',
             'Fribourg',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202009,
             202,
             'GL',
             'Glarus',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202011,
             202,
             'JU',
             'Jura',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202013,
             202,
             'NE',
             'Neuchâtel',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202015,
             202,
             'OW',
             'Obwalden',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202016,
             202,
             'SH',
             'Schaffhausen',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202018,
             202,
             'SO',
             'Solothurn',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202020,
             202,
             'TG',
             'Thurgau',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202022,
             202,
             'UR',
             'Uri',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202024,
             202,
             'VD',
             'Vaud',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202026,
             202,
             'ZH',
             'Zürich',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8043,
             8,
             'IS',
             'Isernia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8045,
             8,
             'SP',
             'La Spezia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8047,
             8,
             'LE',
             'Lecce',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8049,
             8,
             'LI',
             'Livorno',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8051,
             8,
             'LU',
             'Lucca',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8053,
             8,
             'MN',
             'Mantova',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8055,
             8,
             'MT',
             'Matera',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8057,
             8,
             'ME',
             'Messina',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8059,
             8,
             'MO',
             'Modena',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8061,
             8,
             'NA',
             'Napoli',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8063,
             8,
             'NU',
             'Nuoro',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8065,
             8,
             'OT',
             'Olbia-Tempio',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8067,
             8,
             'PD',
             'Padova',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8069,
             8,
             'PR',
             'Parma',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8071,
             8,
             'PG',
             'Perugia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8073,
             8,
             'PE',
             'Pescara',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8075,
             8,
             'PI',
             'Pisa',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8077,
             8,
             'PN',
             'Pordenone',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8079,
             8,
             'PO',
             'Prato',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8081,
             8,
             'RA',
             'Ravenna',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8083,
             8,
             'RE',
             'Reggio Emilia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8085,
             8,
             'RN',
             'Rimini',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8087,
             8,
             'RO',
             'Rovigo',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8089,
             8,
             'SS',
             'Sassari',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8091,
             8,
             'SI',
             'Siena',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8093,
             8,
             'SO',
             'Sondrio',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8095,
             8,
             'TE',
             'Teramo',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8097,
             8,
             'TO',
             'Torino',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8099,
             8,
             'TN',
             'Trento',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8101,
             8,
             'TS',
             'Trieste',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8103,
             8,
             'VA',
             'Varese',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8105,
             8,
             'VB',
             'Verbano-Cusio-Ossola',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8107,
             8,
             'VR',
             'Verona',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8109,
             8,
             'VI',
             'Vicenza',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (11001,
             11,
             'DR',
             'Drenthe',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (11003,
             11,
             'FR',
             'Friesland',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (11005,
             11,
             'GR',
             'Groningen',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (11007,
             11,
             'NB',
             'Noord-Brabant',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (11009,
             11,
             'OV',
             'Overijssel',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (11011,
             11,
             'ZE',
             'Zeeland',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (15001,
             15,
             'AN',
             'Andalusia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (15003,
             15,
             'AS',
             'Asturias',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (15005,
             15,
             'PV',
             'Basque Country',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (15007,
             15,
             'CB',
             'Cantabria',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (15009,
             15,
             'CM',
             'Castile-La Mancha',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (15011,
             15,
             'CE',
             'Ceuta',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (15013,
             15,
             'GA',
             'Galicia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (15015,
             15,
             'M',
             'Madrid',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (15017,
             15,
             'MU',
             'Murcia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (15019,
             15,
             'VC',
             'Valencia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19002,
             19,
             'AK',
             'Alaska',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19004,
             19,
             'AR',
             'Arkansas',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19006,
             19,
             'CO',
             'Colorado',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19008,
             19,
             'DC',
             'District of Columbia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19010,
             19,
             'FL',
             'Florida',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19012,
             19,
             'HI',
             'Hawaii',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19014,
             19,
             'IL',
             'Illinois',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19016,
             19,
             'IA',
             'Iowa',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19018,
             19,
             'KY',
             'Kentucky ',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19020,
             19,
             'ME',
             'Maine',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19022,
             19,
             'MA',
             'Massachusetts',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19024,
             19,
             'MN',
             'Minnesota',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19026,
             19,
             'MO',
             'Missouri',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19028,
             19,
             'NE',
             'Nebraska',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19030,
             19,
             'NH',
             'New Hampshire',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19032,
             19,
             'NM',
             'New Mexico',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19034,
             19,
             'NC',
             'North Carolina',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19036,
             19,
             'OH',
             'Ohio',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19038,
             19,
             'OR',
             'Oregon',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19040,
             19,
             'PR',
             'Puerto Rico',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19042,
             19,
             'SC',
             'South Carolina',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19044,
             19,
             'TN',
             'Tennessee',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19046,
             19,
             'UT',
             'Utah',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19048,
             19,
             'VA',
             'Virginia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19050,
             19,
             'WV',
             'West Virginia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (19052,
             19,
             'WY',
             'Wyoming',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (32002,
             32,
             'NSW',
             'New South Wales',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (32004,
             32,
             'QLD',
             'Queensland',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (32006,
             32,
             'TAS',
             'Tasmania',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (32008,
             32,
             'WA',
             'Western Australia',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144002,
             144,
             'MX-BCN',
             'Baja California',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144004,
             144,
             'MX-CAM',
             'Campeche',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144006,
             144,
             'MX-CHI',
             'Chihuahua',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144008,
             144,
             'MX-COL',
             'Colima',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144010,
             144,
             'MX-GTO',
             'Guanajuato',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144012,
             144,
             'MX-HGO',
             'Hidalgo',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144014,
             144,
             'MX-MEX',
             'Mexico',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144016,
             144,
             'MX-MOR',
             'Morelos',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144018,
             144,
             'MX-NLE',
             'Nuevo Leon',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144020,
             144,
             'MX-PUE',
             'Puebla',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144023,
             144,
             'MX-ROO',
             'Quintana Roo',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144025,
             144,
             'MX-SIN',
             'Sinaloa',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144027,
             144,
             'MX-TAB',
             'Tabasco',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144029,
             144,
             'MX-TLX',
             'Tlaxcala',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (144031,
             144,
             'MX-YUC',
             'Yucatan',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (164001,
             164,
             '01',
             'Østfold',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (164003,
             164,
             '03',
             'Oslo',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (164005,
             164,
             '05',
             'Oppland',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (164007,
             164,
             '07',
             'Vestfold',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (164009,
             164,
             '09',
             'Aust-Agder',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (164011,
             164,
             '11',
             'Rogaland',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (164013,
             164,
             '14',
             'Sogn og Fjordane',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (164015,
             164,
             '16',
             'Sør-Trøndelag',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (164017,
             164,
             '18',
             'Nordland',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (164019,
             164,
             '20',
             'Finnmark',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202002,
             202,
             'AR',
             'Appenzell Ausserrhoden',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202004,
             202,
             'BL',
             'Basel-Landschaft',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202006,
             202,
             'BE',
             'Bern',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202008,
             202,
             'GE',
             'Geneva',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202010,
             202,
             'GR',
             'Graubünden',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202012,
             202,
             'LU',
             'Lucerne',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202014,
             202,
             'NW',
             'Nidwalden',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202017,
             202,
             'SZ',
             'Schwyz',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202019,
             202,
             'SG',
             'St. Gallen',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202021,
             202,
             'TI',
             'Ticino',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202023,
             202,
             'VS',
             'Valais',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (202025,
             202,
             'ZG',
             'Zug',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (4004,
             4,
             'BB',
             'Brandenburg',
             TRUE);INSERT INTO region (regionid,
                    countryid,
                    regioncode,
                    "name",
                    active_)
     VALUES (8060,
             8,
             'MB',
             'Monza e Brianza',
             TRUE);COMMIT;